### ISSUE TITLE
EPIC: <Initial Install>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#1]
### First Install of the project, add libraries and frameworks needed for basic functionality, hide sensitive data

- [ ] install django, gunicorn, dj_database, psycopg2
- [ ] create env.py file, hide secret key, hide database url
- [ ] create bookings app
