### ISSUE TITLE
EPIC: <Error Pages>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#40]
### Create custom error page templates for 404, 403 and 500 errors.

- [ ] Create 404.html Page #35 
- [ ] Create 403.html Page #36 
- [ ] Create 500.html Page #37
