### ISSUE TITLE
EPIC: <Contact Form>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#42]
### Create an Contact Form and associated model to store contact submissions to the admin panel.

- [ ] Create Contact Model
- [ ] Create Contact Form
- [ ] Create Contact Template
