### ISSUE TITLE
EPIC: <Front End Design>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#45]
### Create templates, a colour scheme, navigation and responsiveness for the website

- [ ] TASK: <UI Design> #31
- [ ] TASK: <Create Templates> #30
- [ ] USER STORY: <Responsive Design> #20
