### ISSUE TITLE
EPIC: <Use Profiles>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#6]
### Allow Users to create/update/manage and delete user profiles

- [ ] Allow user create profile
- [ ] Allow user update profile
- [ ] Allow user delete profile
- [ ] User Login/Logout
