### ISSUE TITLE
EPIC: <Bookings>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/P4-Aventine-Wellness#7]
### Create an app to allow users to book sessions with the yoga teacher

- [ ] Allow user/admin to create bookings
- [ ] Allow user/admin to update/delete bookings
- [ ] Do not allow duplicate bookings
